version: '3.1'

services:
  private:
    image: katta2311/private:8
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: private_service
    ports:
    - 8092:8092
    working_dir: /opt/app
    networks:
    - ingress
networks:
  ingress:
  external: true
